# Generated by Django 4.2.14 on 2024-07-24 23:07

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogpostpage_date_alter_blogpostpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
