# Generated by Django 5.0.7 on 2024-07-24 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blogpostpage_body_alter_blogpostpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogPostPage',
        ),
    ]
