# Generated by Django 4.2.14 on 2024-09-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description for this blog post', max_length=160),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO meta title for this blog post', max_length=100),
        ),
    ]
