# Generated by Django 4.2.14 on 2024-07-24 22:18

from django.db import migrations, models
import django.utils.timezone
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogpostpage_delete_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpage',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='intro',
            field=models.CharField(max_length=250),
        ),
    ]
